field: cafd4b32-060e-4878-9728-5acdd0009f2f # Modules
fieldLayouts:
  d09f2a57-fbfe-449a-a087-3f752d2c3edb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3ce739ff-83c2-4dc0-8704-57139397dc1e # Module Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97ab402c-dafd-4904-8f61-7bcc69d01110
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 48803a6f-d759-4e3c-899c-e90b40b998db
        userCondition: null
fields:
  3ce739ff-83c2-4dc0-8704-57139397dc1e: # Module Video
    columnSuffix: gdnsypxa
    contentColumnType: text
    fieldGroup: null
    handle: moduleVideo
    instructions: null
    name: 'Module Video'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: moduleVideo
name: 'Module Video'
sortOrder: 2
